# docker compose run web python manage.py {test,makemigrations,migrate}

name: cambridge-vote
services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  static:
    build:
      dockerfile: Dockerfile.static
    develop:
      watch:
        - action: rebuild
          path: ./static_src
          target: /app/static_src
    # command: watch
    volumes:
      # mounting as a file so that we can npm update and see the changes
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./webpack.config.json:/app/webpack.config.json
      - ./static_src:/app/static_src
      - ./static_compiled:/app/static_compiled
  web:
    build:
      dockerfile: Dockerfile.django
      args:
        REQ_ENV: dev
    develop:
      watch:
        - action: sync
          path: ./django_app
          target: /app
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # static_compiled is checked in to avoid compile for deploys
      - ./static_compiled:/app/static_compiled
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DATABASE_URL=postgresql://postgres:postgres@db/postgres
      - DJANGO_SETTINGS_MODULE=citycouncil.settings
      - DJANGO_SECRET_KEY=testtest
      - DJANGO_DEBUG=TRUE
      - DJANGO_ALLOWED_HOST=*
      - GOOGLE_EMBED_API_KEY=AIzaSyCcioP2q-I1l11gotDDN7-suOclEmR5eVo
    links:
      - db
    depends_on:
      - static
volumes:
  staticfiles:
  postgres_data:
  media:
