# docker compose run web python manage.py {test,makemigrations,migrate}

name: cambridge-vote
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  static:
    build:
      dockerfile: Dockerfile.static
    command: watch
    volumes:
      # mounting as a file so that we can npm update and see the changes
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./webpack.config.json:/app/webpack.config.json
      - ./static_src:/app/static_src
      - ./static_compiled:/app/static_compiled
  web:
    build:
      dockerfile: Dockerfile.django
      args:
        REQ_ENV: dev
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static_compiled:/app/static_compiled
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=citycouncil.settings
      - DJANGO_SECRET_KEY=testtest
      - DJANGO_DEBUG=TRUE
      - DJANGO_ALLOWED_HOST=*
    depends_on:
      - db
      - static
volumes:
  staticfiles:
