# docker compose run web python manage.py {test,makemigrations,migrate}

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  static:
    build:
      dockerfile: Dockerfile.static
    command: watch
    volumes:
      - .:/static_src
      - .:/static_compiled
  web:
    build:
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /static_compiled/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=docker_settings
    depends_on:
      - db
