# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_auto_20170618_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='headshot',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
