# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0005_auto_20170625_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='headshot_description',
            field=models.CharField(default='headshot of candidate', max_length=500),
        ),
    ]
