# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0007_merge_20170626_1724"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="headshot",
        ),
    ]
