# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:37
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def add_slug(apps, schema_editor):
    Candidate = apps.get_model("overview.Candidate")
    for candidate in Candidate.objects.filter(slug=""):
        candidate.slug = slugify(candidate.fullname)
        candidate.save()


def remove_slugs(apps, schema_editor):
    Candidate = apps.get_model("overview.Candidate")
    Candidate.objects.all().update(slug="")


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0008_remove_candidate_headshot'),
    ]

    operations = [
        migrations.RunPython(add_slug, reverse_code=remove_slugs),
    ]
