# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0009_auto_20170627_1837"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="website",
            field=models.URLField(blank=True, default="", help_text="Main candidate website"),
        ),
    ]
