# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0017_auto_20170806_2153"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="endorsements_link",
            field=models.URLField(blank=True, default="", help_text="Endorsements List"),
        ),
    ]
