# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0019_auto_20170924_2151"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="campaign_manager",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="candidate",
            name="is_cyclist",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="candidate",
            name="twitter",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="blurb",
            field=models.TextField(blank=True, help_text="Text to display. Publically readable!"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="private_notes",
            field=models.TextField(blank=True),
        ),
    ]
