# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0020_auto_20170924_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('own', 'Own'), ('dorm', 'Dorm'), ('o', 'Other'), ('u', 'Unknown')], default='u', max_length=4),
        ),
    ]
