# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0021_auto_20170924_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='degrees',
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, help_text='like what degrees they have', max_length=200),
        ),
    ]
