# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0024_auto_20171001_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
