# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0026_auto_20171001_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewvideo',
            name='sort_order',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
