# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0027_interviewvideo_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewvideo',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('own', 'Own'), ('dorm', 'Dorm'), ('o', 'Other'), ('u', 'Live')], default='u', max_length=4),
        ),
    ]
