# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0028_auto_20171001_2224'),
        ('overview', '0024_auto_20171001_1246'),
    ]

    operations = [
    ]
