# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0031_auto_20171008_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='facebook',
            field=models.CharField(blank=True, default='', help_text='Candidate facebook page', max_length=100),
        ),
    ]
