# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0035_merge_20171014_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
