# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0036_pastcontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastcontribution",
            name="note",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="pastcontribution",
            name="recipient",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
