# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0036_candidate_timestamp_modified'),
        ('overview', '0037_auto_20171015_1210'),
    ]

    operations = [
    ]
