# Generated by Django 2.2.4 on 2019-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0044_auto_20191020_1833"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="short_history_text",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
