# Generated by Django 2.2.4 on 2021-08-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0045_candidate_short_history_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('fullname',)},
        ),
    ]
