# Generated by Django 2.2.24 on 2021-10-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0048_auto_20211024_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalproposal',
            name='private_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specificproposal',
            name='private_notes',
            field=models.TextField(blank=True),
        ),
    ]
