# Generated by Django 2.2.24 on 2021-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0049_auto_20211024_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificproposal',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
