# Generated by Django 2.2.24 on 2021-10-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0052_auto_20211024_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='housing_is_a_landlord',
            field=models.NullBooleanField(),
        ),
    ]
