# Generated by Django 4.2.5 on 2023-10-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0059_topic_candidate_instagram_candidate_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
