# Generated by Django 4.2.5 on 2023-10-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0062_candidate_nextdoor_alter_pressarticle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reddit',
            field=models.CharField(blank=True, default='', help_text='reddit community, not including reddit url', max_length=100),
        ),
    ]
