# Generated by Django 4.2.5 on 2023-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0063_organization_reddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
