# Generated by Django 4.2.5 on 2023-10-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0065_alter_specificproposal_order"),
        ("overview", "0066_alter_endorsement_candidate_and_more"),
    ]

    operations = []
