# Generated by Django 4.2.5 on 2023-10-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0072_vanelection_candidate_van_id_candidate_van_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanelection',
            name='van_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
