# Generated by Django 4.2.5 on 2023-10-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0074_alter_vanelection_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatevan",
            name="voted",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
