# Generated by Django 4.2.5 on 2023-10-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0075_alter_candidatevan_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevan',
            name='political_party',
            field=models.CharField(blank=True, choices=[('dem', 'Democrat'), ('rep', 'Republican'), ('o', 'Other'), ('u', 'Unknown')], default=None, max_length=3, null=True),
        ),
    ]
