# Generated by Django 4.2.5 on 2023-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0078_forum_forumparticipant_forumorganization"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="moderators",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="forum",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
