# Generated by Django 5.2.5 on 2025-09-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0081_election_candidateelection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="address",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="blurb",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="campaign_manager",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="checked_fec_for_contributions",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="checked_ocpf_for_contributions",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="cpf_id",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="date_of_registration",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="education",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="email",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="endorsements_link",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="headshot_description",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="hide",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_blurb",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_is_a_landlord",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_private_notes",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_sale_date",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_sale_price",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_sale_price_inflation",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_sell_value",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_status",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_status_note",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="housing_type",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="is_cyclist",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="is_incumbent",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="is_running",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="job",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="more_running_info",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="n_terms_in_council",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="n_terms_on_school_committee",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="n_time_running_for_council",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="neighborhood",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="nextdoor",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="place_of_birth",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="political_party",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="previous_results_map",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="private_notes",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="self_loan",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="short_history_text",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="van_id",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="van_phone",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="voter_id_number",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="voter_status",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="website",
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="blurb",
            field=models.TextField(blank=True, help_text="Text to display. Publically readable!"),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="campaign_manager",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="checked_fec_for_contributions",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="checked_ocpf_for_contributions",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="cpf_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="date_of_registration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="education",
            field=models.CharField(
                blank=True, help_text="like what degrees they have", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="endorsements_link",
            field=models.URLField(blank=True, default="", help_text="Endorsements List"),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="facebook",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Candidate facebook page, not including facebook url",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="headshot_description",
            field=models.CharField(default="headshot of candidate", max_length=500),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="hide",
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_blurb",
            field=models.TextField(blank=True, help_text="Text to display. Publically readable!"),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_is_a_landlord",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_private_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_sale_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_sale_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_sale_price_inflation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_sell_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rent", "Rent"),
                    ("own", "Own"),
                    ("dorm", "Dorm"),
                    ("o", "Other"),
                    ("u", "Live"),
                ],
                default="u",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_status_note",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="housing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single-Family"),
                    ("double", "Two-Family"),
                    ("triple", "Triple-Decker"),
                    ("apartment", "Apartment"),
                    ("dorm", "Dorm"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="u",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="instagram",
            field=models.CharField(
                blank=True,
                default="",
                help_text="insta, not including instagram url",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="is_cyclist",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="is_incumbent",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="is_running",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="job",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="linkedin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="linkedin, not including linkedin url",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="more_running_info",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="n_terms_in_council",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="n_terms_on_school_committee",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="n_time_running_for_council",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="nextdoor",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="political_party",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dem", "Democrat"),
                    ("rep", "Republican"),
                    ("o", "Other"),
                    ("u", "Unknown"),
                ],
                default="u",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="previous_results_map",
            field=models.URLField(
                blank=True, help_text="previous election results from Davi", null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="private_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="self_loan",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="short_history_text",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="twitter",
            field=models.CharField(
                blank=True,
                default="",
                help_text="twitter, not including twitter url",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="van_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="van_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="voter_id_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="voter_status",
            field=models.CharField(
                blank=True,
                choices=[("A", "Active"), ("I", "Inactive"), ("u", "Unknown")],
                default="u",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="website",
            field=models.URLField(blank=True, default="", help_text="Main candidate website"),
        ),
    ]
