# Generated by Django 5.2.5 on 2025-09-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0083_remove_candidateelection_previous_results_map_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
