# Generated by Django 5.2.5 on 2025-09-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0084_degree_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateEndorsement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=150)),
                ("display", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "candidate_election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="overview.candidateelection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="overview.organization",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Endorsement",
        ),
    ]
