# Generated by Django 5.2.5 on 2025-09-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0087_remove_questionnaire_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateelection",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="candidateelection",
            name="place_of_birth",
        ),
        migrations.AddField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
