# Generated by Django 5.2.5 on 2025-09-14 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0088_remove_candidateelection_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="candidate",
        ),
        migrations.AddField(
            model_name="quote",
            name="candidate_election",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="overview.candidateelection",
            ),
            preserve_default=False,
        ),
    ]
