# Generated by Django 5.2.5 on 2025-09-16 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0089_remove_quote_candidate_quote_candidate_election"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewvideo",
            name="candidate",
        ),
        migrations.AddField(
            model_name="interviewvideo",
            name="candidate_election",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="overview.candidateelection",
            ),
            preserve_default=False,
        ),
    ]
