# Generated by Django 5.2.5 on 2025-09-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0082_candidate_headshot_alter_organization_logo_and_more"),
        ("overview", "0090_remove_interviewvideo_candidate_and_more"),
    ]

    operations = []
