# Generated by Django 5.2.5 on 2025-09-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0091_merge_20250916_1858"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="headshot",
        ),
        migrations.AddField(
            model_name="candidateelection",
            name="headshot",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
