# Generated by Django 5.2.5 on 2025-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0096_alter_forum_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
