# Generated by Django 5.2.5 on 2025-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0097_election_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateelection",
            name="fundraising_info_url",
            field=models.URLField(
                blank=True, default="", help_text="External websites with fundraising breakdown"
            ),
        ),
    ]
