# Generated by Django 5.2.5 on 2025-09-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0099_candidate_wikipedia_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressarticlecandidate",
            name="display",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="display",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="questionnaireresponse",
            name="display",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="display",
            field=models.BooleanField(default=True),
        ),
    ]
