# Generated by Django 5.2.5 on 2025-10-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0102_interviewvideo_blurb_interviewvideo_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="cite",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
