# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fullname", models.CharField(max_length=200)),
                ("shortname", models.CharField(max_length=200)),
                (
                    "pronoun",
                    models.CharField(
                        choices=[("she", "She"), ("he", "He"), ("they", "They")], max_length=4
                    ),
                ),
            ],
        ),
    ]
