# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_incumbent",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="is_running",
            field=models.NullBooleanField(),
        ),
    ]
