# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0002_auto_20170618_1753"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
