# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0006_candidate_headshot_description"),
        ("overview", "0004_auto_20170625_1928"),
    ]

    operations = []
