# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0010_candidate_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidate",
            name="notes",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="candidate",
            name="political_party",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dem", "Democrat"),
                    ("rep", "Republican"),
                    ("o", "Other"),
                    ("u", "Unknown"),
                ],
                default="u",
                max_length=3,
            ),
        ),
    ]
