# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0012_candidate_facebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
