# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0023_auto_20170924_2303"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="date_of_registration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="voter_id_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="candidate",
            name="voter_status",
            field=models.CharField(
                blank=True,
                choices=[("A", "Active"), ("I", "Inactive"), ("u", "Unknown")],
                default="u",
                max_length=3,
            ),
        ),
    ]
