# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0029_merge_20171001_2239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewvideo",
            name="sort_order",
            field=models.FloatField(blank=True),
        ),
    ]
