# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0034_candidate_previous_results_map"),
        ("overview", "0034_auto_20171014_1902"),
    ]

    operations = []
