# Generated by Django 2.2.24 on 2021-10-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0047_auto_20211024_1129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalproposal",
            name="shortname",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="specificproposal",
            name="shortname",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
