# Generated by Django 4.2.5 on 2023-10-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0061_alter_organization_is_local_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="nextdoor",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="pressarticle",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
