# Generated by Django 5.2.5 on 2025-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0081_election_candidateelection"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="headshot",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="pressoutlet",
            name="logo",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
