# Generated by Django 5.2.5 on 2025-09-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0085_candidateendorsement_delete_endorsement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CandidateGeneralProposalStance",
        ),
    ]
