# Generated by Django 5.2.5 on 2025-09-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0086_delete_candidategeneralproposalstance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="year",
        ),
        migrations.RemoveField(
            model_name="questionnaireresponse",
            name="candidate",
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="election",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="overview.election",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="candidate_election",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="overview.candidateelection",
            ),
            preserve_default=False,
        ),
    ]
