# Generated by Django 5.2.5 on 2025-09-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0092_remove_candidate_headshot_candidateelection_headshot"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidateelection",
            unique_together={("candidate", "election")},
        ),
    ]
