# Generated by Django 5.2.5 on 2025-09-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0093_alter_candidateelection_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateelection",
            name="headshot",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
