# Generated by Django 5.2.5 on 2025-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0094_alter_candidateelection_headshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="pressoutlet",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
