# Generated by Django 5.2.5 on 2025-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0095_alter_organization_logo_alter_pressoutlet_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="year",
            field=models.IntegerField(default=2025, null=True),
        ),
    ]
