# Generated by Django 5.2.5 on 2025-09-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0098_candidateelection_fundraising_info_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="wikipedia_page",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
