# Generated by Django 5.2.5 on 2025-10-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0100_alter_pressarticlecandidate_display_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateelection",
            name="city_website",
            field=models.URLField(blank=True, default="", help_text="Official city blurb site"),
        ),
    ]
