# Generated by Django 5.2.5 on 2025-10-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0101_candidateelection_city_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewvideo",
            name="blurb",
            field=models.TextField(
                blank=True,
                default="",
                help_text="additional information (ex., if there's one video but this is a specific question in it)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="interviewvideo",
            name="end_time",
            field=models.IntegerField(blank=True, help_text="end for youtube", null=True),
        ),
        migrations.AddField(
            model_name="interviewvideo",
            name="start_time",
            field=models.IntegerField(blank=True, help_text="start for youtube", null=True),
        ),
        migrations.AddField(
            model_name="interviewvideo",
            name="title",
            field=models.TextField(
                blank=True, default="", help_text="title in the video system", max_length=200
            ),
        ),
    ]
