# Generated by Django 5.2.5 on 2025-10-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0103_alter_quote_cite"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateelection",
            name="timestamp_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
