# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 21:49
from __future__ import unicode_literals

from django.db import migrations
import csv
import datetime


def load_initial_donations(apps, schema_editor):
    rcr = apps.get_model('campaign_finance.RawCampaignReceipt')

    fp = open('campaign_finance/migrations/cambridge_donors_2017-07-15.csv', 'r')
    donors_csv = csv.DictReader(fp, delimiter="\t")

    for row in donors_csv:

        d = datetime.datetime.strptime(row["Date"], "%m/%d/%Y")
        if d.year > 2014:

            rcr.objects.create(
                recipient_cpf_id=row["Recipient CPF ID"],
                recipient_full_name=row["Recipient Full Name"],
                date=d,
                first_name=row["First Name"],
                last_name=row["Last Name"],
                address=row["Address"],
                city=row["City"],
                state=row["State"],
                zip=row["Zip"],
                occupation=row["Occupation"],
                employer=row["Employer"],
                principal_officer=row["Principal Officer"],
                contributor_id=row["Contributor ID"],
                is_inkind=row["Is Inkind"],
                amount=row["Amount"]
            )


def unload_initial_donations(apps, schema_editor):
    rcr = apps.get_model('campaign_finance.RawCampaignReceipt')

    rcr.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_donations, reverse_code=unload_initial_donations)
    ]
