# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_finance', '0002_auto_20170715_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawBankReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocpf_id', models.IntegerField()),
                ('report_id', models.IntegerField()),
                ('report_type_id', models.IntegerField()),
                ('report_type_description', models.CharField(max_length=200)),
                ('cpf_id', models.IntegerField()),
                ('full_name_reverse', models.CharField(max_length=200)),
                ('report_candidate_first_name', models.CharField(max_length=200)),
                ('report_year', models.IntegerField()),
                ('ending_date_display', models.DateField(blank=True, null=True)),
                ('beginning_date_display', models.DateField(blank=True, null=True)),
                ('reporting_period', models.CharField(max_length=200)),
                ('filing_id', models.IntegerField()),
                ('filing_date', models.DateTimeField(blank=True, null=True)),
                ('filing_date_display', models.DateField(blank=True, null=True)),
                ('filing_date_short_display', models.DateField(blank=True, null=True)),
                ('filing_mechanism', models.CharField(max_length=200)),
                ('is_amended', models.BooleanField(default=0)),
                ('is_amendment', models.BooleanField(default=0)),
                ('amendment_reason', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('beginning_balance_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_total_display', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_unitemized_total_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_itemized_total_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenditure_unitemized_total_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenditure_itemized_total_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenditure_total_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ending_balance_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inkind_total_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liability_total_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payments_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_total_display', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ui', models.CharField(max_length=20)),
                ('reimbursee', models.CharField(max_length=200)),
            ],
        ),
    ]
