# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_finance', '0004_auto_20170716_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCleaned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cleaned', models.DateField(blank=True, null=True)),
                ('who_cleaned', models.CharField(max_length=200)),
                ('how_cleaned', models.CharField(max_length=200)),
                ('field_changed', models.CharField(choices=[('recipient_cpf_id', 'Recipient cpf id'), ('recipient_full_name', 'Recipient full name'), ('date', 'Date'), ('first_name', 'First name'), ('last_name', 'Last name'), ('address', 'Address'), ('city', 'City'), ('state', 'State'), ('zip', 'zip'), ('occupation', 'Occupation'), ('employer', 'Employer'), ('principal_officer', 'Principal officer'), ('contributor_id', 'Contributor ID'), ('is_inkind', 'Is inkind'), ('amount', 'Amount')], max_length=19)),
                ('old_value', models.CharField(max_length=200)),
                ('new_value', models.CharField(max_length=200)),
                ('raw_receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_finance.RawCampaignReceipt')),
            ],
        ),
        migrations.RemoveField(
            model_name='cleancampaignreceipt',
            name='occupation_type',
        ),
        migrations.AddField(
            model_name='cleancampaignreceipt',
            name='raw_receipt_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='campaign_finance.RawCampaignReceipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawbankreport',
            name='receipt_total_display',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
