# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_finance", "0004_auto_20170716_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawbankreport",
            name="receipt_total_display",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
