# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_finance', '0005_auto_20170722_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleancampaignreceipt',
            old_name='raw_receipt_id',
            new_name='raw_receipt',
        ),
    ]
