# Generated by Django 2.2.3 on 2019-10-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_finance", "0006_auto_20191019_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawbankreport",
            name="cpf_id",
            field=models.IntegerField(db_index=True),
        ),
    ]
