# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0003_auto_20171015_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankedelement",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
