# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 00:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0005_auto_20171028_2158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankedlist",
            name="owner",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
