# Generated by Django 2.2.4 on 2021-08-11 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0007_rankedlist_ordered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankedlist",
            name="owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
