# Generated by Django 5.2.5 on 2025-09-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0093_alter_candidateelection_unique_together"),
        ("ranking", "0008_auto_20210810_2147"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankedlist",
            name="election",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="overview.election"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rankedelement",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="overview.candidateelection"
            ),
        ),
    ]
