# Generated by Django 5.2.5 on 2025-09-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overview", "0099_candidate_wikipedia_page"),
        ("ranking", "0010_alter_rankedlist_owner"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rankedlist",
            unique_together={("election", "slug")},
        ),
        migrations.AlterField(
            model_name="rankedlist",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.RemoveField(
            model_name="rankedlist",
            name="public",
        ),
    ]
