# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20171010_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankedelement',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='rankedlist',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
