# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0004_auto_20171028_1731"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankedlist",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
