# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20171031_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedlist',
            name='ordered',
            field=models.BooleanField(default=True),
        ),
    ]
